### ISSUE TITLE
RequestError [HttpError]: Not Found

### ISSUE THREAD

**Issue by cognitivim** [commercetools/github-labels#13]
## Steps to Reproduce
```console
$ github-labels init
RequestError [HttpError]: Not Found
```

("@commercetools/github-labels": "1.0.2")

## Current Behavior
Incorrect request url:
```console
request: {
    method: 'GET',
    url: 'https://api.github.com/repos/https://github.com/CognitiveLaunchpad/cogn-project-template/https://github.com/CognitiveLaunchpad/cogn-project-template/labels',
   ...
```

<details><summary>Full output: </summary>

```console
$ github-labels init
RequestError [HttpError]: Not Found
    at /Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async fetchLabels (/Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@commercetools/github-labels/lib/api.js:26:20)
    at async writeLabelsConfig (/Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@commercetools/github-labels/lib/index.js:67:18)
    at async /Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@commercetools/github-labels/bin/glm:57:9 {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, ' +
      'X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, ' +
      'X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, ' +
      'X-GitHub-Media-Type',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 23 Jun 2019 19:37:09 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.symmetra-preview; format=json',
    'x-github-request-id': '33BC:35F87:79FD2D4:9945C8D:5D0FD4E5',
    'x-oauth-scopes': 'repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4953',
    'x-ratelimit-reset': '1561322229',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/https://github.com/CognitiveLaunchpad/cogn-project-template/https://github.com/CognitiveLaunchpad/cogn-project-template/labels',
    headers: {
      accept: 'application/vnd.github.symmetra-preview+json',
      'user-agent': 'octokit.js/16.28.2 Node.js/12.4.0 (macOS Mojave; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'https://developer.github.com/v3'
}

  GITHUB LABEL MANAGER

    Usage: ./bin/glm [command] [option]

      Commands:
        init        Initializes the label manager. It creates a new label-config.json
                    file with the current label data of your repository.

        sync        Uploads all changes you've made in the label-config.json file
                    into the repository to update the label with the given changes.
  
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

</details>

## Expected Behavior
Correct parsing git remote origin url

## Possible Solution
That following code deals only with SSH protocol:
https://github.com/commercetools/github-labels/blob/fca16df2b17907c271c8f080e9af66475bd1abf4/lib/utils.js#L9

Please add support to `git` and `HTTP/HTTPS` protocols
(https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-push.html#URLS)

**Comment by TimonRey** [comment]
Hi @cognitivim! Greetings from Germany! Thank you for your contribution, I really appreciate that! It was very helpful! 💯 
I merged this PR to solve the issue: #16
